name: Deploy My Digital Card

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Check encodeProfileData configuration
        id: check-config
        run: |
          ENCODE_PROFILE_DATA=$(node -pe "require('./src/config/config.json').encodeProfileData")
          echo "ENCODE_PROFILE_DATA=$ENCODE_PROFILE_DATA" >> $GITHUB_ENV

      - name: Prepare profile data (encodeProfileData= true)
        if: env.ENCODE_PROFILE_DATA == 'true'
        run: |
          if [ -f public/data/b64ProfileData.json ]; then
            echo "b64ProfileData.json already exists."
          else
            if [ -f src/data/profileData.json ]; then
              npm run prebuild
            else
              cp src/data/profileData.template.json src/data/profileData.json
              npm run prebuild
            fi
          fi

      - name: Prepare profile data (encodeProfileData= false)
        if: env.ENCODE_PROFILE_DATA == 'false'
        run: |
          if [ ! -f src/data/profileData.json ]; then
            cp src/data/profileData.template.json src/data/profileData.json
            npm run prebuild
          fi

      - name: Build project
        run: |
          PUBLIC_URL="https://$(echo $GITHUB_REPOSITORY | awk -F / '{print tolower($1)}').github.io/$(echo $GITHUB_REPOSITORY | awk -F / '{print tolower($2)}')" npm run build
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          CI: false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          commit_message: 'Deploy to GitHub Pages from ${{ github.sha }}'
