name: Deploy My Digital Card

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Check encodeProfileData configuration
        id: check-config
        run: |
          ENCODE_PROFILE_DATA=$(node -pe "require('./src/config/config.json').encodeProfileData")
          echo "ENCODE_PROFILE_DATA=$ENCODE_PROFILE_DATA" >> $GITHUB_ENV

      - name: Prepare profile data (encodeProfileData= true)
        if: env.ENCODE_PROFILE_DATA == 'true'
        run: |
          if [ -f public/data/b64ProfileData.json ]; then
            echo "b64ProfileData.json already exists."
          else
            if [ -f src/data/profileData.json ]; then
              npm run prebuild
            else
              cp src/data/profileData.template.json src/data/profileData.json
              npm run prebuild
            fi
          fi

      - name: Prepare profile data (encodeProfileData= false)
        if: env.ENCODE_PROFILE_DATA == 'false'
        run: |
          if [ ! -f src/data/profileData.json ]; then
            cp src/data/profileData.template.json src/data/profileData.json
            npm run prebuild
          fi

      - name: Build project
        run: npm run build
        env:
          CI: false

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: 'gh-pages'

      - name: Copy files
        run: |
          cp -r build/* gh-pages/

      - name: Commit and push
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy updates"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
